import { halfLogo } from "../images";

export default [
  {
    id: "1",
    category: "일식",
    store: "크레이지카츠",
    minPrice: 12000,
    delivTip: 3500,
    people: 1,
  },
  {
    id: "2",
    category: "카페",
    store: "설빙",
    minPrice: 13000,
    delivTip: 2500,
    people: 2,
  },
  {
    id: "3",
    category: "중식",
    store: "홍콩반점",
    minPrice: 15000,
    delivTip: 1500,
    people: 2,
  },
  {
    id: "4",
    category: "한식",
    store: "한솥도시락",
    minPrice: 9000,
    delivTip: 3500,
    people: 2,
  },
  {
    id: "5",
    category: "일식",
    store: "이자카야",
    minPrice: 10000,
    delivTip: 3500,
    people: 1,
  },
  {
    id: "6",
    category: "일식",
    store: "카츠카츠",
    minPrice: 11000,
    delivTip: 3500,
    people: 2,
  },
  {
    id: "7",
    category: "한식",
    store: "바비든든",
    minPrice: 7000,
    delivTip: 3500,
    people: 1,
  },
  {
    id: "8",
    category: "한식",
    store: "김가네",
    minPrice: 15000,
    delivTip: 3500,
    people: 1,
  },
  {
    id: "9",
    category: "일식",
    store: "덮밥킹",
    minPrice: 12000,
    delivTip: 3500,
    people: 2,
  },
  {
    id: "10",
    category: "양식",
    store: "롤링파스타",
    minPrice: 11000,
    delivTip: 3500,
    people: 1,
  },
  {
    id: "11",
    category: "한식",
    store: "바르다김선생",
    minPrice: 15000,
    delivTip: 3500,
    people: 2,
  },
  {
    id: "12",
    category: "일식",
    store: "크레이지카츠",
    minPrice: 12000,
    delivTip: 3500,
    people: 1,
  },
  {
    id: "13",
    category: "카페",
    store: "설빙",
    minPrice: 13000,
    delivTip: 3500,
    people: 2,
  },
  {
    id: "14",
    category: "중식",
    store: "홍콩반점",
    minPrice: 15000,
    delivTip: 3500,
    people: 2,
  },
  {
    id: "15",
    category: "한식",
    store: "한솥도시락",
    minPrice: 9000,
    delivTip: 3500,
    people: 2,
  },
  {
    id: "16",
    category: "일식",
    store: "이자카야",
    minPrice: 10000,
    delivTip: 3500,
    people: 1,
  },
  {
    id: "17",
    category: "일식",
    store: "카츠카츠",
    minPrice: 11000,
    delivTip: 3500,
    people: 2,
  },
  {
    id: "18",
    category: "한식",
    store: "바비든든",
    minPrice: 7000,
    delivTip: 3500,
    people: 1,
  },
  {
    id: "19",
    category: "한식",
    store: "김가네",
    minPrice: 15000,
    delivTip: 3500,
    people: 1,
  },
  {
    id: "20",
    category: "일식",
    store: "덮밥킹",
    minPrice: 12000,
    delivTip: 3500,
    people: 2,
  },
  {
    id: "21",
    category: "양식",
    store: "롤링파스타",
    minPrice: 11000,
    delivTip: 3500,
    people: 1,
  },
  {
    id: "22",
    category: "한식",
    store: "바르다김선생",
    minPrice: 15000,
    delivTip: 3500,
    people: 2,
  },
  {
    id: "23",
    category: "일식",
    store: "크레이지카츠",
    minPrice: 12000,
    delivTip: 3500,
    people: 1,
  },
  {
    id: "24",
    category: "카페",
    store: "설빙",
    minPrice: 13000,
    delivTip: 3500,
    people: 2,
  },
  {
    id: "25",
    category: "중식",
    store: "홍콩반점",
    minPrice: 15000,
    delivTip: 3500,
    people: 2,
  },
  {
    id: "26",
    category: "한식",
    store: "한솥도시락",
    minPrice: 9000,
    delivTip: 3500,
    people: 2,
  },
  {
    id: "27",
    category: "일식",
    store: "이자카야",
    minPrice: 10000,
    delivTip: 3500,
    people: 1,
  },
  {
    id: "28",
    category: "일식",
    store: "카츠카츠",
    minPrice: 11000,
    delivTip: 3500,
    people: 2,
  },
  {
    id: "29",
    category: "한식",
    store: "바비든든",
    minPrice: 7000,
    delivTip: 3500,
    people: 1,
  },
  {
    id: "30",
    category: "한식",
    store: "김가네",
    minPrice: 15000,
    delivTip: 3500,
    people: 1,
  },
  {
    id: "31",
    category: "일식",
    store: "덮밥킹",
    minPrice: 12000,
    delivTip: 3500,
    people: 2,
  },
  {
    id: "32",
    category: "양식",
    store: "롤링파스타",
    minPrice: 11000,
    delivTip: 3500,
    people: 1,
  },
  {
    id: "33",
    category: "한식",
    store: "바르다김선생",
    minPrice: 15000,
    delivTip: 3500,
    people: 2,
  },
];
