import React, { Component, useState, useEffect } from "react";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  centerize: {
    flex: 1,
    alignItems: "center", // 가로 정렬
    justifyContent: "center", // 세로 정렬
    paddingVertical: 100,
  },
  rootCategoryButtons: {
    flexDirection: "row",
    // padding: 2,
    backgroundColor: "#fff",
    // alignContent: "center",
    justifyContent: "space-evenly",
  },
  orderLogImage: {
    marginBottom: 10,
    // flex: 1,
    height: 70,
    width: 70,
    resizeMode: "contain", //? Show whole Image (with white space)
    alignSelf: "center",
    borderRadius: 5,
    borderWidth: 1,
  },
  orderLogCategory: {
    fontSize: 40,
    fontFamily: "noto-regular",
    fontWeight: "bold",
    textAlign: "left",
  },
  orderLogMinPrice: {
    fontSize: 30,
    fontFamily: "noto-regular",
    fontWeight: "bold",
    textAlign: "left",
  },
  textInput: {
    height: 40,
    width: "80%",
    margin: 10,
    borderWidth: 1,
    padding: 10,
  },
  storeList: {
    borderRadius: 10,
    marginBottom: 5,
    padding: 2,
    backgroundColor: "grey",
    justifyContent: "center",
  },
  h75col: {
    width: "95%",
    borderRadius: 10,
    height: "75%",
    marginBottom: 5,
    padding: 10,
    backgroundColor: "lightgrey",
    justifyContent: "center",
    flexDirection: "column",
    flexWrap: "wrap",
  },
  h25grey: {
    width: "95%",
    height: "25%",
    borderRadius: 10,
    marginBottom: 5,
    padding: 10,
    backgroundColor: "lightgrey",
    alignItems: "center",
    justifyContent: "center",
    flex: 3.5,
  },
  orderLog: {
    width: "95%",
    height: "25%",
    borderRadius: 10,
    marginBottom: 5,
    padding: 20,
    backgroundColor: "lightgrey",
    // alignItems: "center",
    // justifyContent: "center",
    // flex: 3.5,
  },
  h25greyCenter: {
    width: "95%",
    height: "25%",
    borderRadius: 10,
    marginBottom: 5,
    padding: 10,
    backgroundColor: "lightgrey",
    alignItems: "center",
    justifyContent: "center",
    flex: 3.5,
  },
  h25col: {
    width: "95%",
    borderRadius: 10,
    height: "25%",
    marginBottom: 5,
    padding: 10,
    backgroundColor: "lightgrey",
    justifyContent: "center",
    flexDirection: "column",
    flexWrap: "wrap",
  },
  h25row: {
    width: "95%",
    borderRadius: 10,
    height: "25%",
    marginBottom: 5,
    padding: 10,
    backgroundColor: "lightgrey",
    alignItems: "center",
    flex: 3.5,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  h10row: {
    width: "95%",
    borderRadius: 10,
    height: "10%",
    marginTop: 2,
    marginBottom: 20,
    paddingVertical: 2,
    backgroundColor: "lightgrey",
    alignItems: "center",
    justifyContent: "space-evenly",
    flexDirection: "row",
  },
  h10rowBottom: {
    width: "95%",
    borderRadius: 10,
    height: "10%",
    marginTop: 20,
    marginBottom: 20,
    paddingVertical: 2,
    backgroundColor: "lightgrey",
    alignItems: "center",
    justifyContent: "space-evenly",
    flexDirection: "row",
  },

  pressed: {
    backgroundColor: "skyblue",
    width: "auto",
    borderRadius: 10,
    padding: 5,
    margin: 10,
  },
  notPressed: {
    backgroundColor: "lightgrey",
    width: "auto",
    borderRadius: 10,
    padding: 5,
    margin: 10,
  },
  headerText: {
    fontSize: 15,
    fontFamily: "noto-regular",
    fontWeight: "bold",
  },
  textPressed: {
    color: "white",
    textAlign: "center",
    fontSize: 30,
    fontFamily: "noto-regular",
  },
  textNotPressed: {
    color: "white",
    textAlign: "center",
    fontSize: 40,
    fontFamily: "noto-regular",
  },
});

export default styles;
